In [5]:
import numpy as np

In [6]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype="int64")
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int64)

In [7]:
a.max(axis=0)

array([7, 8, 9], dtype=int64)

In [8]:
a*[[2,3,4]]

array([[ 2,  6, 12],
       [ 8, 15, 24],
       [14, 24, 36]], dtype=int64)

In [9]:
a*[[2],[3],[4]]

array([[ 2,  4,  6],
       [12, 15, 18],
       [28, 32, 36]], dtype=int64)

In [10]:
a.max(axis=1)

array([3, 6, 9], dtype=int64)

In [14]:
b=z[:2]
b

[0, 2]

In [ ]:
e=z[1:2,1:2]
e=b.max()


In [ ]:
z[0]

In [ ]:
z=np.array([[1,2,3,4,5],[9,10,7,6,8],[15,12,14,13,11],[19,18,20,16,17],[24,22,25,21,23]],dtype="int64")
z

In [ ]:
d=np.ones((5,5),dtype="int64")
d

In [ ]:

for x in range(5):
    for y in range(5):
        if x==0:
            d[x][y]=z[x][y]
        elif y==0:
            d[x][y]=z[x][y]
        else:
            d[x][y]=max(z[x][y-1],z[x-1][y-1],z[x-1][y])
print(d)

In [ ]:
s=np.array(A)
print(s)
t=s.reshape(5,5)
t

In [ ]:
def max_array(m,n,main_arr,dummy_arr):
    m=int(input("Enter no. of rows    : "))
    n=int(input("Enter no. of columns : "))
    total=m*n
    l=[input("enter the value for index no. {} : ".format(i)) for i in range(total)]
    arr=np.array(l,dtype="int64")
    main_arr=arr.reshape(m,n)
    print("\nThe main array is : \n{}\n".format(main_arr))
    dummy_arr=np.ones((m,n),dtype="int64")
    for x in range(m):
        for y in range(n):
            if x==0:
                dummy_arr[x,y]=main_arr[x,y]
            elif y==0:
                dummy_arr[x,y]=main_arr[x,y]
            else:
                dummy_arr[x,y]=max(main_arr[x,y-1],main_arr[x-1,y-1],main_arr[x-1,y])
    print("Required array :\n{}".format(dummy_arr))
max_array(m,n,main_arr,dummy_arr)

In [ ]:
z

In [ ]:
x=np.arange(0,9)
a=np.array([x,np.ones(9)])
a

In [ ]:
m_a=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype="int64")
d_a=np.ones((3,3),dtype="int64")

In [ ]:
a=np.arange(1,17)
print(a,"\n")
print("The dimension of the array : ",a.ndim,"\n")
b=a.reshape(4,2,2)
print(b,"\n")
print("The dimension of the array : ",b.ndim,"\n")
c=np.ones((3,3),dtype="int64")
print(f"itemsize for {c.dtype} is {c.itemsize} bytes \n")

In [ ]:
a={}
b="geeksforgeeks"
for i in b:
    if i in a:
        a[i]+=1
    else:
        a[i]=1
print(a)

In [ ]:
import numpy as np
import time as t
value =100
def python_version():
    t1=t.time()
    x=range(value)
    y=range(value)
    z=[x[i]+y[i] for i in range(len(x))]
    return t1

def numpy_version():
    t2=t.time()
    a=np.arange(value)
    b=np.arange(value)
    c=a+b
    return t2
print(f"python version speed : {python_version()}\nnumpy version speed : {numpy_version()}")
print(f"numpy is {python_version()/numpy_version()} times faster than python")