In [1]:
import numpy as np

In [4]:
b=np.array([[2,3,4],[5,6,7],[8,9,10],[11,12,13]],dtype="int64")

In [24]:
type(b)

numpy.ndarray

In [29]:
b.shape

(4, 3)

In [30]:
b.dtype

dtype('int64')

In [31]:
b.size

12

In [6]:
dir(b)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [13]:
y=np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
y.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
np.arange(1,11,1.2)

array([ 1. ,  2.2,  3.4,  4.6,  5.8,  7. ,  8.2,  9.4, 10.6])

In [41]:
np.linspace(1,11,3)

array([ 1.,  6., 11.])

In [42]:
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]], dtype=int64)

In [46]:
b.max()

13

In [47]:
b.min()

2

In [49]:
b[:2,:3]

array([[2, 3, 4],
       [5, 6, 7]], dtype=int64)

In [59]:
b%2!=0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [60]:
b[b%2!=0]

array([ 3,  5,  7,  9, 11, 13], dtype=int64)

In [55]:
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]], dtype=int64)

In [24]:
z=np.concatenate((b,[[14,15,16],[17,18,19]]))
z

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]], dtype=int64)

In [20]:
y=np.concatenate((b,[[20],[30],[40],[50]]),axis=1)
y

array([[ 2,  3,  4, 20],
       [ 5,  6,  7, 30],
       [ 8,  9, 10, 40],
       [11, 12, 13, 50]], dtype=int64)

In [21]:
z.shape

(6, 3)

In [22]:
y.shape

(4, 4)

In [26]:
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]], dtype=int64)

In [27]:
b.max(axis=0)

array([11, 12, 13], dtype=int64)

In [28]:
b.max(axis=1)

array([ 4,  7, 10, 13], dtype=int64)

In [29]:
b.min(axis=0)

array([2, 3, 4], dtype=int64)

In [30]:
b.min(axis=1)

array([ 2,  5,  8, 11], dtype=int64)

In [63]:
b*=2

In [6]:
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]], dtype=int64)

In [7]:
b*[[10],[20],[30],[40]]

array([[ 20,  30,  40],
       [100, 120, 140],
       [240, 270, 300],
       [440, 480, 520]], dtype=int64)

In [65]:
b//=2
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]], dtype=int64)

In [69]:
np.hsplit(b,3)

[array([[ 2],
        [ 5],
        [ 8],
        [11]], dtype=int64), array([[ 3],
        [ 6],
        [ 9],
        [12]], dtype=int64), array([[ 4],
        [ 7],
        [10],
        [13]], dtype=int64)]

In [71]:
np.vsplit(b,4)

[array([[2, 3, 4]], dtype=int64),
 array([[5, 6, 7]], dtype=int64),
 array([[ 8,  9, 10]], dtype=int64),
 array([[11, 12, 13]], dtype=int64)]

In [73]:
np.hstack((b,b))

array([[ 2,  3,  4,  2,  3,  4],
       [ 5,  6,  7,  5,  6,  7],
       [ 8,  9, 10,  8,  9, 10],
       [11, 12, 13, 11, 12, 13]], dtype=int64)

In [74]:
np.vstack((b,b))

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]], dtype=int64)

In [76]:
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]], dtype=int64)

In [75]:
b.argmax(axis=1)

array([2, 2, 2, 2], dtype=int64)

In [77]:
b.argmin(axis=1)

array([0, 0, 0, 0], dtype=int64)

In [79]:
b.argmax(axis=0)

array([3, 3, 3], dtype=int64)

In [80]:
b.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [82]:
b.astype("int64")

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]], dtype=int64)

In [107]:
b.shape

(4, 3)

In [105]:
x=b.transpose()
x

array([[ 2,  5,  8, 11],
       [ 3,  6,  9, 12],
       [ 4,  7, 10, 13]], dtype=int64)

In [108]:
x.shape

(3, 4)

In [3]:
c=np.eye(3)
d = np.ones((3, 3))*2
print("np.eye :",c,"\n")
print("np.one :",d)

np.eye : [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

np.one : [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [103]:
c.dot(d)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [106]:
b.dot(x)

array([[ 29,  56,  83, 110],
       [ 56, 110, 164, 218],
       [ 83, 164, 245, 326],
       [110, 218, 326, 434]], dtype=int64)

In [109]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_

In [115]:
np.append(b,[[14],[15],[16],[17]],axis=1)

array([[ 2,  3,  4, 14],
       [ 5,  6,  7, 15],
       [ 8,  9, 10, 16],
       [11, 12, 13, 17]], dtype=int64)

In [116]:
np.append(b,[[14,15,16]],axis=0)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]], dtype=int64)

In [2]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a.max(axis=1)

array([3, 6, 9])

In [13]:
a.itemsize

4

In [12]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.max(a)

9